#!/bin/sh -e

# Set the password in the pScheduler database to match what's on the
# disk.
( \
    printf "ALTER ROLE pscheduler WITH PASSWORD '" \
    && tr -d "\n" < "/etc/pscheduler/database/database-password" \
    && printf "';\n" \
) | postgresql-load
echo "Password set"

exit 0
